spring.application.name=world-roster-challenge
server.port=8080

game.players.resource=classpath:data/players.json
game.rules.draft-options=3
game.rules.group-size=4
game.rules.group-round-robins=2
game.rules.group-qualifiers=2
game.rules.knockout-wins-required=3
